name: Matrix Demo
on: push
jobs:
  build:
    strategy: 
        matrix:
            os: [ubuntu-latest, windows-latest]
            node-version: [14, 16, 18]
    runs-on: ${{ matrix.os }} #job will run for both runners
    steps:
        - name: Get Code
          uses: actions/checkout@v4
        - name: Install NodeJS
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }} #job will run for all node versions, ubuntu-14,16,18 ; windows-14,16,18; total 6 runs
        - name: Install Dependencies
          run: npm run ci
        - name: Build Project
          run: npm run build