name: Reusable Deploy
on: 
  workflow_call: #Run this wf from inside other wf
    inputs:
        artifact-name:
          description: Name of the Deployable Artifact file
          required: true
          type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v4 #to download artifact from build step in use-reusable.yml
        with:
          name: ${{ inputs.artifact-name }} #same name from use-reusable.yml
      - name: List files
        run: ls
      - name: Output Information
        run: echo "Deploying & Uploading"
      
