name: Using Reusable Workflow
on:
  push:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Test code
        id: run-tests
        run: npm run test
      - name: Upload test report
        if: failure() &&  steps.run-tests.outcome == 'failure' #outcome has [success, failure, cancelled, skipped], conclusion field is also there
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true' #when cache-hit is false then install dependencies will happen
        run: npm ci
      - name: Build website
        id: build-website
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    uses: ./.github/workflows/reusable.yml #path to reusable wf
    with: 
       artifact-name: dist-files #Artifact file given to reusable WF as input
    # secrets:
    #     some-secret: ${{secrets.some-secret}}
  print-deploy-result:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Print deploy Output
      run: echo ${{ needs.deploy.outputs.result }}
  report:
    needs: [lint, deploy]
    if: failure() #This job will run if any other job fails
    runs-on: ubuntu-latest 
    steps:
      - name: Output Information
        run: |
          echo "Something Went wrong!"
          echo "${{ toJson(github) }}" 

